### ISSUE TITLE
Android resource compilation failed

### ISSUE THREAD

**Issue by Fraid** [smooch/smooch-android#115] opened 2018-05-15 15:33 UTC
Hi guys,

I know it’s early but I got following error from Android Studio 3.2 Preview when using  `com.android.tools.build:gradle:3.2.0-alpha14`  :

```
Android resource compilation failed
Output:  /Users/foo/Android_Development/testtest/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:717: error: <item> inner element must either be a resource reference or empty.
/Users/foo/Android_Development/testtest/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:718: error: <item> inner element must either be a resource reference or empty.
/Users/foo/Android_Development/testtest/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:719: error: <item> inner element must either be a resource reference or empty.
/Users/foo/Android_Development/testtest/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:720: error: <item> inner element must either be a resource reference or empty.
/Users/foo/Android_Development/testtest/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:721: error: <item> inner element must either be a resource reference or empty.
/Users/foo/Android_Development/testtest/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:722: error: <item> inner element must either be a resource reference or empty.
/Users/foo/Android_Development/testtest/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:723: error: <item> inner element must either be a resource reference or empty.
/Users/foo/Android_Development/testtest/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:743: error: <item> inner element must either be a resource reference or empty.

Command: /Users/foo/.gradle/caches/transforms-1/files-1.1/aapt2-3.2.0-alpha14-4748712-osx.jar/029b7626041099202e32811089fb25a7/aapt2-3.2.0-alpha14-4748712-osx/aapt2 compile --legacy \
        -o \
        /Users/foo/Android_Development/testtest/app/build/intermediates/res/merged/debug \
        /Users/foo/Android_Development/testtest/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml
Daemon:  AAPT2 aapt2-3.2.0-alpha14-4748712-osx Daemon #0
```

It’s easy to reproduce, just create an empty project with build tool version **_3.2.0-alpha14_** . And the following dependencies:
```
implementation 'io.smooch:core:5.12.1'
implementation 'io.smooch:ui:5.12.1'
```

After somme research this seem to be linked with following resources:

```
    <item name="cc_card" type="id">2222</item>
    <item name="cc_ccv" type="id">4444</item>
    <item name="cc_entry" type="id">1000</item>
    <item name="cc_entry_internal" type="id">3000</item>
    <item name="cc_exp" type="id">3333</item>
    <item name="cc_form_layout" type="id">1111</item>
    <item name="cc_zip" type="id">5555</item>
    <item name="custom" type="id"/>
```
I have been using Android studio Preview (from canary channel) for month now because the release version is slow on mac os hight sierra.

**Comment by sanjukurian** [comment] 2018-05-29 13:37
Any updates on this?

**Comment by jugarrit** [comment] 2018-05-29 13:38
We haven't had a chance to take a look at this yet, we'll keep you updated once we do.
Thanks for understanding.

**Comment by wmora** [comment] 2018-05-29 19:10
Should be fixed in version [5.12.3](https://github.com/smooch/smooch-android/releases/tag/5.12.3)

**Closed by wmora** 2018-05-29 19:10 UTC

**Comment by joejensen8** [comment] 2018-06-27 00:54
I'm having this same issue.
AS Preview Beta 1
Android Build Tools 3.2.0-beta01
implementation 'io.smooch:core:5.13.1'
implementation 'io.smooch:ui:5.13.1'

**Comment by zaiwang** [comment] 2018-07-03 13:39
how to deal with this issue, thanks, same issue in my project.

**Comment by wmora** [comment] 2018-07-04 13:07
The [demo app](https://github.com/smooch/smooch-android/tree/master/demo) is working for me with:

AS Preview Beta 2
Android Build Tools 3.2.0-beta02
implementation 'io.smooch:core:5.13.1'
implementation 'io.smooch:ui:5.13.1'

**Comment by TusharGogna** [comment] 2018-07-05 06:11
I have the same issue. Can someone tell why this error occurs?

**Comment by romshiri** [comment] 2018-07-09 22:14
Same issue...

**Comment by wmora** [comment] 2018-07-10 13:09
is it possible to provide a sample project reproducing the issue? It's working for me using the demo app with the latest AS preview

**Comment by pratheepchowdhary** [comment] 2018-07-14 06:57
Follow this syntax 
<item name="custom" type="id"/>

I

**Comment by wmora** [comment] 2018-07-17 14:05
@pratheepchowdhary do you mean adding that resource to my app? Because I couldn't reproduce the issue by doing that

**Comment by GuptaMunna** [comment] 2018-07-29 12:05
same issue anyone got the answer

**Comment by pedrofsn** [comment] 2018-08-10 01:02
Same problem

**Comment by alavers** [comment] 2018-08-10 02:32
@pratheepchowdhary @GuptaMunna @pedrofsn 👀 https://github.com/smooch/smooch-android/issues/115#issuecomment-403815978

**Comment by pedrofsn** [comment] 2018-08-10 14:53
Active proguard and you'll see app crashing. It's probably happen because proguard are removing some classes and methods of library, so we need specify what is really needed for every possible case. How I need move on, I accepted evertything of the library as a non excluding file to proguard.

@alavers

**Comment by wmora** [comment] 2018-08-13 18:07
@pedrofsn running Proguard may fail because of a missing Glide method. If the error you are getting is

```
com.bumptech.glide.load.resource.bitmap.VideoDecoder: can't find referenced method 'android.graphics.Bitmap getScaledFrameAtTime(long,int,int,int)' in library class android.media.MediaMetadataRetriever
```

Add the following to your proguard config. We'll include it in our next release:

```
-dontwarn com.bumptech.glide.load.resource.bitmap.VideoDecoder
```

**Comment by anoopdunamis** [comment] 2018-09-25 07:17
cvzfsgs

**Comment by szee45** [comment] 2018-10-03 12:52
I was also having the same error but I removed all nonresourece item from resource file. And it is working fine now.

**Comment by landsnail** [comment] 2018-10-12 07:52
it seems that the lastest version of android which is 28 will not work the format like :
<item name="cc_card" type="id">2222</item> 

change to : 

<item name="cc_card" type="id" />

it mean that google will not allow self define id values any more, after all the item fix , it really work.

**Comment by landsnail** [comment] 2018-10-12 07:52
it seems that the lastest version of android which is 28 will not work the format like :
```
<item name="cc_card" type="id">2222</item> 
```
change to : 
```
<item name="cc_card" type="id" />
```
it mean that google will not allow self define id values any more, after all the item fix , it really work.

**Comment by rabidh052** [comment] 2018-10-20 13:38
![error](https://user-images.githubusercontent.com/43547991/47256307-9afd9a00-d49f-11e8-9d32-cbedfda415ed.PNG)

how to solve this problem?

**Comment by Almaral-Engineering** [comment] 2018-10-24 19:05
Same problem here, started with Android Studio 3.2.1 and buildToolsVersion '28.0.3', but I cannot modify the autogenerated files, they generate again

**Comment by n-sviridenko** [comment] 2018-10-29 21:22
Same

**Comment by loopq** [comment] 2018-10-30 03:40
same.How to fix?

**Comment by jilleb** [comment] 2018-10-31 14:03
Same here, AS 3.2.1 and buildTools 28.0.3... Tried it with 26.0.2, still the same issue.

**Comment by wmora** [comment] 2018-11-05 22:04
what SDK version are you using? Can you provide a sample project or setup that reproduces the issue? I haven't been able to reproduce, unfortunately

**Comment by Rahmatbd** [comment] 2019-01-10 14:53
Android resource compilation failed
Output:  values_values.arsc.flat: error: failed to open.

Command: C:\Users\EZZECASH\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.1-4818971-windows.jar\6fd25df41b5b28f816048a23d6a0b147\aapt2-3.2.1-4818971-windows\aapt2.exe compile --legacy \
        -o \
        C:\Users\EZZECASH\Desktop\AhleHaq\app\build\intermediates\res\merged\debug \
        C:\Users\EZZECASH\Desktop\AhleHaq\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml
Daemon:  AAPT2 aapt2-3.2.1-4818971-windows Daemon #0

**Comment by shane-harris** [comment] 2019-01-10 18:47
I have this same issue. someone please help

**Comment by shane-harris** [comment] 2019-01-10 19:17
SOLVED!!!
Ok so there hasn't been a clear explanation to solve this issue but i just figured it out.
Thanks to landsnail. His explanation was correct but not geared to someone who has never built an app. So here is the step by step.

Go into your app project.
Navigate to the Resources folder (res)
Open values folder
Open ids.xml
-- This should show you the list of all items that you created in the .xml files in the layouts folder
Each item should be of the format <item name="???" type="id></item>
the question marks should contain the id that you assigned the item that you created in your layouts files.
DO NOT put the name in be the name of the item in between <item>???</item>. 
here is an example of what i did wrong
<item name="child_text" type="id">childText</item>
this is what i did to correct it
<item name="child_text" type="id"></item>

there MUST be an <item> for ever item that you created in your various layout .xml files.

Hope this helps someone

**Comment by SharkFourSix** [comment] 2019-10-02 16:01
If you have an Antivirus or Antimalware service running somewhere, make sure you add exemptions to everything under Android Studio and the Sdk in (%applocaldata%)


Check also that Windows Defender's Controlled Folder Access  is On or Off and that you have added AS files on the whitelist. Restart Android Studio and the problem should be fixed.

**Comment by 19860917013** [comment] 2021-05-15 10:33
> ![error](https://user-images.githubusercontent.com/43547991/47256307-9afd9a00-d49f-11e8-9d32-cbedfda415ed.PNG)
> 
> how to solve this problem?

solved？

**Comment by Ahmadkaj** [comment] 2021-05-16 13:51
same issue

**Comment by Ahmadkaj** [comment] 2021-05-16 13:53
Failed to compile values file. how to fix this issue 

this is my build.gradle

plugins {
    id 'com.android.application'
}

android {
    compileSdkVersion 29
    buildToolsVersion "30.0.2"

    defaultConfig {
        applicationId "com.example.truthordarelebaneeseversion"
        minSdkVersion 16
        targetSdkVersion 29
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {

    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'com.google.android.material:material:1.2.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.1'
    testImplementation 'junit:junit:4.+'
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
}

**Comment by Mayurjag** [comment] 2021-05-31 20:03
Same Issue

**Comment by bhaskarkatara** [comment] 2024-07-04 07:56
> Follow this syntax `<item name="custom" type="id"/>`

yes this works for me ,thank you
