### ISSUE TITLE
Concurrent modification exception occurs at Smooch service.

### ISSUE THREAD

**Issue by andinrajesh** [smooch/smooch-android#49] opened 2016-09-09 13:53 UTC

**Comment by jugarrit** [comment] 2016-09-09 14:22
Please provide a stack trace to help me understand the problem.

**Comment by andinrajesh** [comment] 2016-09-12 11:31
java.util.ConcurrentModificationException
                                                                  at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
                                                                  at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:95)
                                                                  at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:60)
                                                                  at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:68)
                                                                  at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:113)
                                                                  at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:240)
                                                                  at com.google.gson.Gson.toJson(Gson.java:605)
                                                                  at com.google.gson.Gson.toJson(Gson.java:584)
                                                                  at com.google.gson.Gson.toJson(Gson.java:539)
                                                                  at com.google.gson.Gson.toJson(Gson.java:519)
                                                                  at io.smooch.core.b.a.c.a(Unknown Source)
                                                                  at io.smooch.core.b.c.a(Unknown Source)
                                                                  at io.smooch.core.service.SmoochService.n(Unknown Source)
                                                                  at io.smooch.core.service.SmoochService.c(Unknown Source)
                                                                  at io.smooch.core.service.SmoochService.a(Unknown Source)
                                                                  at io.smooch.core.service.SmoochService$10$1.a(Unknown Source)
                                                                  at io.smooch.core.service.SmoochService$10$1.a(Unknown Source)
                                                                  at io.smooch.core.b.f$7.a(Unknown Source)
                                                                  at io.smooch.core.b.a.b$1$2.run(Unknown Source)
                                                                  at android.os.Handler.handleCallback(Handler.java:739)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                  at android.os.Looper.loop(Looper.java:148)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by ancloid** [comment] 2016-12-22 13:42
I have a lot of those errors.

[Screenshot](https://www.dropbox.com/s/ljgootg61s43sso/Screenshot%202016-12-22%2015.34.50.png?dl=0)

It happens after **onResume()** method and on some ugly devices like:
Asus ME371MG, Samsung GT-N8000, Samsung SM-T211, HUAWEI HUAWEI Y300-0100, Lge
 LG-F160L, Sony Ericsson LT26w etc

**Only on Android 16, 4.1.1 or 4.1.2**

**Comment by wmora** [comment] 2016-12-22 13:54
@ancloid thanks for the detail! We'll look into it

**Comment by praveencastelino** [comment] 2017-04-20 08:44
Will it be fixed soon? This is is a show stopper for us before going to production.

**Comment by wmora** [comment] 2017-04-20 13:26
@praveencastelino we haven't been able to debug this issue, unfortunately. It is added to our backlog and will talk to the team to prioritize it

**Comment by praveencastelino** [comment] 2017-04-20 13:40
@wmora Thanks a lot. I hope it gets fixed soon...We have a deep integration of smooch SDK integration with our app. The crash is random and breaks the user flow :(

**Comment by jugarrit** [comment] 2017-05-12 15:40
The latest version [4.6.0](https://github.com/smooch/smooch-android/releases/tag/4.6.0) includes an attempted fix for the crash described here.
Seeing as it's difficult to reproduce, please let us know if you see it happen again and we'll take another look.

Hope we've seen the end of it.

**Comment by wmora** [comment] 2017-06-20 20:33
Closing this issue since a fix was included in version 4.6.0. Feel free to reopen if it happens again

**Comment by cuiti** [comment] 2017-08-14 17:40
Hey guys, I'm sorry but I think this crash is still happening in 4.6.1.
It has shown up twice in Firebase Crash Reporting in the last few days, and it's a small new app (about a hundred installs)
The devices are LG M250 with android 7.0, and Motorola MotoE2(4G-LTE) with android 6.0.

The stacktrace was:

> Exception java.util.ConcurrentModificationException:
> java.util.ArrayList$Itr.next (ArrayList.java:831)
> com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write (CollectionTypeAdapterFactory.java:95)
> com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write (CollectionTypeAdapterFactory.java:60)
> com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write (TypeAdapterRuntimeTypeWrapper.java:68)
> com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write (ReflectiveTypeAdapterFactory.java:113)
> com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write (ReflectiveTypeAdapterFactory.java:240)
> com.google.gson.Gson.toJson (Gson.java:605)
> com.google.gson.Gson.toJson (Gson.java:584)
> com.google.gson.Gson.toJson (Gson.java:539)
> com.google.gson.Gson.toJson (Gson.java:519)
> io.smooch.core.b.a.c.a ()
> io.smooch.core.b.c.a ()
> io.smooch.core.service.SmoochService.a ()
> io.smooch.core.service.SmoochService.b ()
> io.smooch.core.service.SmoochService$10$1.a ()
> io.smooch.core.service.SmoochService$10$1.a ()
> io.smooch.core.b.f$7.a ()
> io.smooch.core.b.a.b$1$2.run ()
> android.os.Handler.handleCallback (Handler.java:751)
> android.os.Handler.dispatchMessage (Handler.java:95)
> android.os.Looper.loop (Looper.java:154)
> android.app.ActivityThread.main (ActivityThread.java:6312)
> java.lang.reflect.Method.invoke (Method.java)
> com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:872)
> com.android.internal.os.ZygoteInit.main (ZygoteInit.java:762)

**Comment by comgra** [comment] 2017-10-13 07:50
@cuiti hi cuiti, have you find how to avoid it?

**Comment by comgra** [comment] 2017-10-13 10:13
@jugarrit @wmora hi guys, it happens again in 5.0.1

**Comment by cuiti** [comment] 2017-10-13 11:41
@comgra I haven't found a solution. This issue should be reopened

**Comment by jugarrit** [comment] 2017-10-13 13:26
Dupe of https://github.com/smooch/smooch-android/issues/98

**Closed** 2017-10-13 13:26 UTC
