### ISSUE TITLE
ConversationActivity crashing when rendering smoochButtons

### ISSUE THREAD

**Issue by carlosdejavite** [smooch/smooch-android#45] opened 2016-09-01 17:46 UTC
For api version 16 and when you send an action button to the user, the ConversationActivity crashes due to java.lang.ArrayIndexOutOfBoundsException: length=16; index=17 at android.widget.RelativeLayout$LayoutParams.addRule(RelativeLayout.java:1204)
at io.smooch.ui.widget.MessageView.addSmoochButton

**Comment by IlyaEremin** [comment] 2016-09-02 05:34
duplicate of #43

**Comment by jugarrit** [comment] 2016-09-06 12:46
Closing since it's a dupe

**Closed by jugarrit** 2016-09-06 12:46 UTC
