### ISSUE TITLE
smooch_btn_send_normal.png: Duplicate file error

### ISSUE THREAD

**Issue by tomredman** [smooch/smooch-android#23] opened 2016-05-09 21:26 UTC
Hey there! 

I'm not quite sure what changed, but I'm getting this error now when syncing Gradle:
`...android-app/build/intermediates/res/merged/dev/debug/drawable-xhdpi-v4/smooch_btn_send_normal.png: error: Duplicate file.`

`...android-app/build/intermediates/res/merged/dev/debug/drawable-xhdpi/smooch_btn_send_normal.png: Original is here. The version qualifier may be implied.`

<img width="951" alt="screen shot 2016-05-09 at 5 23 27 pm" src="https://cloud.githubusercontent.com/assets/4225378/15128605/d0c923a8-160a-11e6-87e5-0487c668c353.png">

I'm using build tools 22.0.1 (unchanged) and including the following in our gradle.build file:

```
compile 'io.smooch:core:latest.release'
compile 'io.smooch:ui:latest.release'
```

Any thoughts on this one? I've tried a full clean, rebuild, etc.

Thanks!

**Comment by jugarrit** [comment] 2016-05-10 13:41
I'll take a look! Thanks for reporting

**Comment by jugarrit** [comment] 2016-05-10 14:17
@tomredman, if you use

```
compile 'io.smooch:core:3.0.0'
compile 'io.smooch:ui:3.0.0'
```

Does the error reproduce?

**Comment by tomredman** [comment] 2016-05-10 14:58
@jugarrit Yes, setting the version to `3.0.0` is reproducible. The error goes away with `2.3.1`.

**Comment by jugarrit** [comment] 2016-05-10 15:37
What version of gradle are you using?
Could you try the following:
`classpath 'com.android.tools.build:gradle:2.1.0'`

**Comment by tomredman** [comment] 2016-05-10 15:40
@jugarrit, We've been using `classpath 'com.android.tools.build:gradle:2.1.0'`. Our stack is a bit sensitive to version changes at the moment, but I'll see if I can give this a shot.

**Comment by tomredman** [comment] 2016-05-11 12:47
Hey @jugarrit, yes I am still seeing this with: `classpath 'com.android.tools.build:gradle:2.1.0'`

**Comment by jugarrit** [comment] 2016-05-11 13:44
Damn... I think that you can temporarily avoid this error by placing the drawable in drawable-xhdpi-v4, but I would like to understand what's causing this problem.

**Comment by jugarrit** [comment] 2018-02-23 14:10
It's been a long time since we've had activity here, so I'm going to close this issue.
Feel free to open a new one if this comes back.

**Closed by jugarrit** 2018-02-23 14:10 UTC
Labels: bug
