### ISSUE TITLE
ConversationActivity.show(this) crashed application with the exception Didn't find class \"io.smooch.ui.R$layout\" on path: DexPathList

### ISSUE THREAD

**Issue by Nikkdroid** [smooch/smooch-android#53] opened 2016-10-07 09:46 UTC
Hi,

I am trying to integrate Smooch in my Android application, I have completed all the steps mentioned in the link - 

http://docs.smooch.io/android/#configuring-push-notifications

But, the app is getting crashed with the exception - 

"stackTrace":"java.lang.NoClassDefFoundError: Failed resolution of: Lio/smooch/ui/R$layout;\n\tat io.smooch.ui.ConversationActivity.setup(Unknown Source)\n\tat io.smooch.ui.ConversationActivity.onCreate(Unknown Source)\n\tat android.app.Activity.performCreate(Activity.java:6303)\n\tat android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)\n\tat android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2376)\n\tat android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2483)\n\tat android.app.ActivityThread.access$900(ActivityThread.java:153)\n\tat android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349)\n\tat android.os.Handler.dispatchMessage(Handler.java:102)\n\tat android.os.Looper.loop(Looper.java:148)\n\tat android.app.ActivityThread.main(ActivityThread.java:5438)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)\nCaused by: java.lang.ClassNotFoundException: Didn\u0027t find class \"io.smooch.ui.R$layout\" on path: DexPathList[[zip file \"/data/app/com.exclusife.business-1/base.apk\"],nativeLibraryDirectories\u003d[/data/app/com.exclusife.business-1/lib/arm, /data/app/com.exclusife.business-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]\n\tat dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)\n\tat java.lang.ClassLoader.loadClass(ClassLoader.java:511)\n\tat java.lang.ClassLoader.loadClass(ClassLoader.java:469)\n\t... 14 more\n\tSuppressed: java.lang.ClassNotFoundException: io.smooch.ui.R$layout\n\t\tat java.lang.Class.classForName(Native Method)\n\t\tat java.lang.BootClassLoader.findClass(ClassLoader.java:781)\n\t\tat java.lang.BootClassLoader.loadClass(ClassLoader.java:841)\n\t\tat java.lang.ClassLoader.loadClass(ClassLoader.java:504)\n\t\t... 15 more\n\tCaused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available\njava.lang.ClassNotFoundException: Didn\u0027t find class \"io.smooch.ui.R$layout\" on path: DexPathList[[zip file \"/data/app/com.exclusife.business-1/base.apk\"],nativeLibraryDirectories\u003d[/data/app/com.exclusife.business-1/lib/arm, /data/app/com.exclusife.business-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]\n\tat dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)

Can some one please help me out with this issue. 

Thanks in advance - Nikesh Yadav

**Comment by wmora** [comment] 2016-10-07 13:11
Hi, could you provide a bit more information about your project (steps for reproducing, is multidex enabled, compileSdkversion, etc)?

If you have just added the smooch library as a dependency, did you clean your project before running it again?

**Comment by ranbeuer** [comment] 2017-02-16 23:11
Hello, I'm also having this issue, I added the libraries from jar to my project, and at first I got the following error: 
`android.content.ActivityNotFoundException: Unable to find explicit activity class {com.unipagos/io.smooch.ui.ConversationActivity}; have you declared this activity in your AndroidManifest.xml?
                                                                  at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1885)
                                                                  at android.app.Instrumentation.execStartActivity(Instrumentation.java:1579)
                                                                  at android.app.Activity.startActivityForResult(Activity.java:3934)
                                                                  at android.app.Activity.startActivityForResult(Activity.java:3894)
                                                                  at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:748)
                                                                  at android.app.Activity.startActivity(Activity.java:4221)
                                                                  at android.app.Activity.startActivity(Activity.java:4189)
                                                                  at io.smooch.ui.ConversationActivity.show(Unknown Source)
                                                                  at io.smooch.ui.ConversationActivity.show(Unknown Source)
                                                                  at com.unipagos.app.settings.SettingsFragment$SupportChatTextViewOnClickListener.onClick(SettingsFragment.java:1175)
                                                                  at android.view.View.performClick(View.java:5207)
                                                                  at android.view.View$PerformClick.run(View.java:21168)
                                                                  at android.os.Handler.handleCallback(Handler.java:746)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                  at android.os.Looper.loop(Looper.java:148)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5459)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)`

After that I included the activity in the manifest but then I got this error:
`java.lang.RuntimeException: Unable to start activity ComponentInfo{com.unipagos/io.smooch.ui.ConversationActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2429)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2493)
                      at android.app.ActivityThread.-wrap11(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1357)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:148)
                      at android.app.ActivityThread.main(ActivityThread.java:5459)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
                   Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
                      at android.support.v7.app.AppCompatDelegateImplBase.onCreate(AppCompatDelegateImplBase.java:112)
                      at android.support.v7.app.AppCompatDelegateImplV7.onCreate(AppCompatDelegateImplV7.java:148)
                      at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:60)
                      at io.smooch.ui.ConversationActivity.onCreate(Unknown Source)
                      at android.app.Activity.performCreate(Activity.java:6259)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1130)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2382)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2493) 
                      at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1357) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:148) 
                      at android.app.ActivityThread.main(ActivityThread.java:5459) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618) `

After adding `android:theme="@style/Theme.AppCompat"` to the activity line in the manifest I got the same error @Nikkdroid describes at the top.

**Comment by wmora** [comment] 2017-02-17 14:30
@ranbeuer both errors seem to suggest that the library resources were not imported. We provide an `AndroidManifest.xml` declaring `ConversationActivity` which should be merged at build time with your application's `AndroidManifest.xml` and the layout causing the crash is probably `smooch_activity_conversation` which is also provided by the library.

May I have more information on how you are importing the libraries? Are you importing them with Gradle? Manually importing the `aar` files? If you could provide a snippet from your app's `build.gradle` it would be great.

**Comment by ranbeuer** [comment] 2017-02-17 16:19
@wmora as I was saying those only appeared while I didn't have the activity declared in my `AndroidManifest.xml`.

After I did those changes I started getting the same error @Nikkdroid described.

Here's mostly of my `build.gradle`

`
android {
    compileSdkVersion 23
    buildToolsVersion "23.0.1"

    useLibrary 'org.apache.http.legacy'

    defaultConfig {
        applicationId "com.unipagos"
        minSdkVersion 15
        targetSdkVersion 22
        multiDexEnabled true
        ndk {
            moduleName "security"
            abiFilters "armeabi-v7a", "armeabi"
        }
    }

    dexOptions {
        javaMaxHeapSize "2g"
    }
    ...
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
        }
    }

    // add this task as a dependency of Java compilation
    tasks.withType(JavaCompile) {
        compileTask -> compileTask.dependsOn ndkBuild
    }

    lintOptions {
        checkReleaseBuilds false
        // Or, if you prefer, you can continue to check for errors in release builds,
        // but continue the build even when errors are found:
        abortOnError false
    }
...
}

dependencies {
    compile 'com.android.support:appcompat-v7:23.0.0' //THIS GUY
//    provided fileTree(dir: 'libs', include: ['*.jar'])
    compile files('libs/ePOS2.jar')
    compile files('libs/sc-light-jdk15on-1.47.0.2.jar')
//Smooch.io libraries
    compile files('libs/core-4.0.7-classes.jar')
    compile files('libs/ui-4.0.7-classes.jar')
//Smooch.io libraries
//    compile files('libs/scpkix-jdk15on-1.47.0.2.jar')
    compile files('libs/scprov-jdk15on-1.47.0.2.jar')
    compile 'com.facebook.android:facebook-android-sdk:4.6.0'
    compile 'com.google.android.gms:play-services-analytics:9.4.0'
    compile 'com.google.android.gms:play-services-maps:9.4.0'
    compile 'com.google.android.gms:play-services-gcm:9.4.0'
    compile 'com.google.android.gms:play-services-location:9.4.0'
//    compile 'com.google.android.gms:play-services:8.4.0'
    compile 'com.android.support:multidex:1.0.1'
    compile 'com.google.code.gson:gson:2.4'
    compile 'com.github.hotchemi:android-rate:1.0.1'
    compile 'com.squareup.okhttp:okhttp:2.4.0'
    compile 'com.github.gcacace:signature-pad:1.2.0'
    compile 'io.card:android-sdk:5.3.2'
//marked some Firebase error which I don't have in my project and don't intend to migrate to from GCM
//    compile 'io.smooch:core:latest.release' 
//    compile 'io.smooch:ui:latest.release'
    compile 'io.conekta:conektasdk:2.0'
}`

As you can see I included the jars directly because I got an error of FIrebase not being included in the project after I included the libraries directly with gradle.

**Comment by wmora** [comment] 2017-02-17 17:13
@ranbeuer thanks for the detail and for providing your `build.gradle` file. Our libraries are published as Android libraries, so only including the jars is not enough as the SDK relies on static resources in order to work.

If you want to keep working with your current Play Services configuration and our latest SDK, you can force the version of the play services and firebase libraries used by our SDK.

Ex:

```
def playServicesVersion = '9.4.0'

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])

    // Add Smooch core and ui
    compile 'io.smooch:core:latest.release'
    compile 'io.smooch:ui:latest.release'

    // Your play services dependencies
    compile "com.google.android.gms:play-services-analytics:${playServicesVersion}"
    compile "com.google.android.gms:play-services-maps:${playServicesVersion}"
    compile "com.google.android.gms:play-services-gcm:${playServicesVersion}"

    // Your play services dependency also used by Smooch
    compile("com.google.android.gms:play-services-location:${playServicesVersion}"){
        force true
    }

    // Firebase libraries used by Smooch
    compile("com.google.firebase:firebase-core:${playServicesVersion}") {
        force = true
    }
    compile("com.google.firebase:firebase-messaging:${playServicesVersion}") {
        force = true
    }
    
    // Your other dependencies
}
```

Let us know if this works for you

**Comment by ranbeuer** [comment] 2017-02-17 20:22
@wmora I did what you said, and updated the appcompat version to 25.1.0 because otherwise it was showing errors. The problem is that now I get this

    Error:Execution failed for task ':unipagos:transformClassesWithJarMergingForMainDebug'.
    > com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: io/smooch/com/devmarvel/creditcardentry/a/a.class

**Comment by ranbeuer** [comment] 2017-02-17 20:35
@wmora nevermind, I just forgot to remove the reference to the jar files in the build.gradle.

Now it is running ok. 

Thanks!

**Comment by wmora** [comment] 2017-02-17 20:41
@ranbeuer awesome!

**Closed by wmora** 2017-02-17 20:42 UTC
