### ISSUE TITLE
Parcelable encountered IOException writing serializable object (name = io.smooch.core.Message)

### ISSUE THREAD

**Issue by abrel** [smooch/smooch-android#114] opened 2018-04-27 21:57 UTC
I am getting the following errors on some of my users.
The crash happens on a Galaxy J3(2016)

Stacktrace is included below.

```android.os.Parcel.writeSerializable (Parcel.java:1394)
android.os.Parcel.writeValue (Parcel.java:1341)
android.os.Parcel.writeArrayMapInternal (Parcel.java:644)
android.os.BaseBundle.writeToParcelInner (BaseBundle.java:1313)
android.os.Bundle.writeToParcel (Bundle.java:1034)
android.os.Parcel.writeBundle (Parcel.java:669)
android.content.Intent.writeToParcel (Intent.java:8414)
android.app.ActivityManagerProxy.broadcastIntent (ActivityManagerNative.java:3344)
android.app.ContextImpl.sendBroadcast (ContextImpl.java:1752)
android.content.ContextWrapper.sendBroadcast (ContextWrapper.java:392)
io.smooch.core.a.b (Unknown Source)
io.smooch.core.a.a (Unknown Source)
io.smooch.core.service.SmoochService.d (Unknown Source)
io.smooch.core.service.SmoochService.c (Unknown Source)
io.smooch.core.service.SmoochService.a (Unknown Source)
io.smooch.core.service.SmoochService.a (Unknown Source)
io.smooch.core.service.SmoochService$8$1.a (Unknown Source)
io.smooch.core.service.SmoochService$8$1.a (Unknown Source)
io.smooch.core.b.f$15.a (Unknown Source)
io.smooch.core.b.a.b$1$2.run (Unknown Source)
android.os.Handler.handleCallback (Handler.java:739)
android.os.Handler.dispatchMessage (Handler.java:95)
android.os.Looper.loop (Looper.java:145)
android.app.ActivityThread.main (ActivityThread.java:6934)
java.lang.reflect.Method.invoke (Method.java)
java.lang.reflect.Method.invoke (Method.java:372)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1404)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1199)```

**Comment by wmora** [comment] 2018-04-30 17:52
which SDK version are you using?

**Comment by abrel** [comment] 2018-05-01 06:59
I am using the latest one 5.12.1

**Comment by wmora** [comment] 2018-05-04 13:28
thanks, do you know if those J3s are running a specific version of Android?

**Comment by Fraid** [comment] 2018-05-04 13:52
Got the same issue seen smooch 5.12.0  .
Mostly with **_Galaxy A3 Android 7_** devices as well, but also with :
_Galaxy S7 Android 7
LG G5 SE  Android 6.0.1
TREKKER-X3 Android 6.0.1_

**Comment by Fraid** [comment] 2018-05-04 13:59
@wmora My bad the dev build used SDK version 5.12.0, but the online one with issue is SDK 5.11.1. And from crashlytics issue started on April 28.

**Comment by abrel** [comment] 2018-05-04 17:00
I see this crash happening for J3 running android 5.1.1
I have also seen it happening for some DOOGEE X10, P8 Lite running android 6.0

More details below:

![image](https://user-images.githubusercontent.com/6062799/39641099-55ac4f98-4fcd-11e8-9a34-8c5cfc8895c2.png)
![image](https://user-images.githubusercontent.com/6062799/39641117-601778f4-4fcd-11e8-89e9-3f8bad20fa90.png)

**Comment by wmora** [comment] 2018-05-08 15:01
I'm not able to reproduce after testing in different devices and OS version, unfortunately :-/. Have you been able to reproduce?

**Comment by Fraid** [comment] 2018-05-08 19:51
Same thing I can't reproduce the issue on my side. 
But from [android-serializable-problem](https://stackoverflow.com/questions/6002800/android-serializable-problem) , look like bitmap should be serializable.
Is it possible the issue come from the Bitmap variable in io.smooch.core.Message ?

**Comment by ykostova** [comment] 2018-05-17 08:19
@wmora I am also able to reproduce the issue after sending and receiving standard textual messages. What is more, once a user experiences it, they are stuck in a crash loop for a while which then gets resolved in some instances. Here is 2 separate stacktraces from 2 different sessions: 

![screen shot 2018-05-17 at 09 15 05](https://user-images.githubusercontent.com/2377138/40165185-423fb9aa-59b3-11e8-9c3e-5a71a2c5cde1.png)
![screen shot 2018-05-17 at 09 14 27](https://user-images.githubusercontent.com/2377138/40165186-42586108-59b3-11e8-9d50-6cc8fe4bed9f.png)

I hope you could get to the bottom of this soon!

**Comment by muja555** [comment] 2018-05-20 16:45
i am able to reproduce this every time on Samsung S7

**Comment by wmora** [comment] 2018-08-13 18:04
Please open a new issue if the issue persists

**Closed by wmora** 2018-08-13 18:04 UTC
